### ISSUE TITLE
Esame 2020-01 \n mancanti

### ISSUE THREAD

**Issue by turbostar190** [euberdeveloper/unitn-tronchet#2]
Ciao, segnalo che le soluzioni dell'esame 2020-01 non contengono i \n relativi agli "a capo" delle istruzioni `System.out.println`.

File: [link](https://github.com/euberdeveloper/unitn-tronchet/blob/master/vuejs/src/schema/data/esame_2020_01.ts)

**Comment by euberdeveloper** [comment]
Grazie, ho corretto
